url: "https://andrewsolis.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Andrew Solis" # the name of your site, e.g. ACME Corp.
domain: "andrewsolis.github.io"